# syntax=docker.io/docker/dockerfile:1
FROM --platform=linux/riscv64 cartesi/python:3.10-slim-jammy

LABEL io.sunodo.sdk_version=0.2.0
LABEL io.cartesi.rollups.ram_size=8Gi

ARG MACHINE_EMULATOR_TOOLS_VERSION=0.12.0
ARG CMAKE_VERSION=3.21.0

COPY ./mmproj-model-f16.gguf .
COPY ./ggml-model-q4_k.gguf .

RUN apt-get update && apt-get install -y --no-install-recommends \
    busybox-static=1:1.30.1-7ubuntu3 \
    ca-certificates \
    curl=7.81.0-1ubuntu1.15 \
    build-essential \
    libssl-dev \
    git \
    autoconf \  
    automake \  
    libtool \    
    pkg-config \
    libsqlite3-0 \ 
    && curl -fsSL https://github.com/cartesi/machine-emulator-tools/releases/download/v${MACHINE_EMULATOR_TOOLS_VERSION}/machine-emulator-tools-v${MACHINE_EMULATOR_TOOLS_VERSION}.tar.gz | \
    tar -C / --overwrite -xvzf - && \
    rm -rf /var/lib/apt/lists/*



RUN curl -LO https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz \
    && tar -zxvf cmake-${CMAKE_VERSION}.tar.gz \
    && cd cmake-${CMAKE_VERSION} \
    && ./bootstrap \
    && make \
    && make install

ENV PATH="/opt/cartesi/bin:${PATH}"

WORKDIR /opt/cartesi/dapp
COPY ./requirements.txt .


RUN pip install --upgrade pip && \
    # Adjust the following line if cmake is handled externally or if alternatives are used
    pip install --find-links https://prototyp3-dev.github.io/pip-wheels-riscv/wheels/ -r requirements.txt --no-cache-dir && \
    find /usr/local/lib -type d -name '__pycache__' -exec rm -r {} +



COPY ./dapp.py .

ENV ROLLUP_HTTP_SERVER_URL="http://127.0.0.1:5004"

ENTRYPOINT ["rollup-init"]
CMD ["python3", "dapp.py"]
